routes/web.php
<?php

use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Support\Facades\Route;

/* @var $localeMiddleware LocaleMiddleware */
$localeMiddleware = app( LocaleMiddleware::class);

\Illuminate\Support\Facades\Auth::routes();

Route::get('cache-clear',function (){
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');

    return redirect()->back()->with('success','Кеш успешно очищено!');
})->name('cache-clear');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('/admin/login', [\App\Http\Controllers\Admin\HomeController::class,'login'])->name('admin.login');

/*********************************************** ADMIN ****************************************************************/
Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::post('/export-table', [\App\Http\Controllers\Admin\ExportTableController::class,'export'])->name('export-table');
    Route::get('/', [\App\Http\Controllers\Admin\HomeController::class,'index'])->name('admin');
    Route::resource('/users-admin', \App\Http\Controllers\Admin\UserAdminController::class);
    Route::get('/users/{id}/{tab}', [\App\Http\Controllers\Admin\UsersController::class,'getTab'])->where('tab', '[a-z0-9-]+');
    Route::post('/users-change-status', [\App\Http\Controllers\Admin\UsersController::class,'changeStatus'])->name('user.change-status');
    Route::resource('/users', \App\Http\Controllers\Admin\UsersController::class);
    Route::post('/pages/menu/add-item', [\App\Http\Controllers\Admin\PagesController::class,'addItem'])->name('page.add-item');
    Route::resource('/pages', \App\Http\Controllers\Admin\PagesController::class);
    Route::resource('/landing', \App\Http\Controllers\Admin\LandingController::class);
    Route::resource('/donors', \App\Http\Controllers\Admin\DonorsController::class);
    Route::post('/plasmacenters/add-social', [\App\Http\Controllers\Admin\PlasmacenterController::class,'addSocial'])->name('plasmacenters.add-social');
    Route::resource('/plasmacenters', \App\Http\Controllers\Admin\PlasmacenterController::class);
    Route::post('menu/move', [\App\Http\Controllers\Admin\MenuController::class,'move']);
    Route::post('menu/rebuild', [\App\Http\Controllers\Admin\MenuController::class,'rebuild']);
    Route::post('menu/add-item', [\App\Http\Controllers\Admin\MenuController::class,'addItem'])->name('menu.add-item');
    Route::post('menu/delete-menu', [\App\Http\Controllers\Admin\MenuController::class,'deleteMenu'])->name('menu.delete-menu');
    Route::post('menu/add-menu', [\App\Http\Controllers\Admin\MenuController::class,'addMenu'])->name('menu.add-menu');
    Route::resource('/menu', \App\Http\Controllers\Admin\MenuController::class);
    Route::resource('/faq', \App\Http\Controllers\Admin\FaqController::class);
    Route::get('settings/{tab}', [\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('add-notice')->where('tab', '[a-z0-9-]+');
    Route::post('settings/save', [\App\Http\Controllers\Admin\SettingsController::class,'save'])->name('settings.save');
    Route::resource('/audio', \App\Http\Controllers\Admin\AudioController::class);
    Route::resource('/audio-categories', \App\Http\Controllers\Admin\AudioCategoryController::class);
    Route::post('/request/status/change', [\App\Http\Controllers\Admin\RequestController::class,'changeStatus'])->name('request.status-change');
    Route::resource('/request', \App\Http\Controllers\Admin\RequestController::class);

    /** BLOG **/
    Route::group(['prefix' => 'blog'], function () {
        Route::resource('/tags', \App\Http\Controllers\Admin\BlogTagsController::class);
        Route::resource('/articles', \App\Http\Controllers\Admin\BlogArticlesController::class);
        Route::get('/subscribe', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'index'])->name('subscribe.index');
        Route::get('/subscribe/list', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'list'])->name('subscribe.list');
    });
});
/************************************ END ADMIN ***********************************************************************/

Route::group(['namespace' => 'Front'], function(){
    Route::any('/{any}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');


    Route::any('/donors/{donor}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');
    Route::any('/{any}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');
});
/*******************************************************************/

app/Models/Landing.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Translatable;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Landing extends Model
{
    use HasFactory;

    use Sluggable;
    use Translatable;

    protected $table = 'landings';

    public $translationModel = 'App\Models\Translations\LandingTranslation';

    public $translatedAttributes = [
        'title',
        'description',
        'meta_title',
        'meta_keywords',
        'meta_description'
    ];

    protected $fillable = [
        'slug',
        'status',
        'menu_id',
        'image'
    ];

    const STATUS_NOT_ACTIVE = 0;
    const STATUS_ACTIVE     = 1;

    public function getDefaultTitleAttribute()
    {
        return $this->translateOrDefault()->title;
    }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public static function getStatuses(): array
    {
        return [
            self::STATUS_NOT_ACTIVE => 'Не активная',
            self::STATUS_ACTIVE     => 'Активная'
        ];
    }

    /**
     * @return array
     */
    public static function getStatusColors(): array
    {
        return [
            self::STATUS_NOT_ACTIVE => ['#ff3838', '#fdfdfd'],
            self::STATUS_ACTIVE     => ['#49cc00', 'white']
        ];
    }

    public function scopeActive($query)
    {
        return $query->where('status', self::STATUS_ACTIVE);
    }

    public function audio()
    {
        return $this->belongsToMany(Audio::class);
    }
}

app/Http/Controllers/Admin/LandingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BlogArticles;
use App\Models\Landing;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Langs;

class LandingController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $status = $request->get('status');
        $title = $request->get('title');

        $model = Landing::query()
                ->leftJoin('landing_translations', 'landing_translations.landing_id', '=', 'landings.id')
                ->where('landing_translations.lang',Langs::getDefaultLangCode())
                ->select([
                    'landings.*',
                    'landing_translations.title'
                ])
            ->orderBy('landings.created_at', 'desc')
            ->where(function ($q) use ($status,$title) {
                if ($status != '') {
                    $q->where('landings.status', $status);
                }
                if ($title != '') {
                    $q->where('landing_translations.title', 'like', '%' . $title . '%');
                }
            })
            ->paginate(20);

        return view('admin.landing.index', [
            'model' => $model
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Landing();

        $localizations = Langs::getLangsWithTitle();

        return view('admin.landing.create', [
            'model'         => $model,
            'localizations' => $localizations
        ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $model = new Landing();

        DB::beginTransaction();

        try {
            if (empty($request->input('slug', ''))) {
                $request->merge(array('slug' => SlugService::createSlug(Landing::class, 'slug', $request->input('page_data.' . Langs::getDefaultLangCode() . '.title'))));
            }

            $model->fill($request->all());

            $model->status = $request->get('status') ?? false;

            if (!$model->save()) {
                DB::rollBack();
            }

            foreach (Langs::getLangsWithTitle() as $lang => $item) {
                $constructorData = $request->get('constructorData');
                $model->translateOrNew($lang)->fill(array_merge($request->input('page_data.' . $lang, []), $constructorData[$lang] ?? []));

                if (!$model->save()) {
                    DB::rollBack();
                }
            }
        } catch (\Throwable $e) {
            DB::rollBack();

            return redirect()->route('landing.index')->with('error', 'Ошибка! ' . $e->getMessage());
        }

        DB::commit();

        return redirect()->route('landing.index')->with('success', 'Лендинг успешно добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * @param Landing $landing
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Landing $landing)
    {
        $localizations = Langs::getLangsWithTitle();

        return view('admin.landing.edit', [
            'model'         => $landing,
            'data'          => $landing->getTranslationsArray(),
            'localizations' => $localizations
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        /* @var $model Landing */
        $model = Landing::query()->where('id', $id)->first();

        DB::beginTransaction();

        try {
            $model->fill($request->all());

            $model->status = $request->get('status') ?? false;

            if (!$model->save()) {
                DB::rollBack();
            }

            $model->deleteTranslations();

            $model->audio()->sync($request->get('audio'));

//            PagesMenu::query()->where('page_id', $model->id)->delete();

//            if ($request->has('menu')) {
//                $order = 0;
//                foreach ($request->get('menu') as $item) {
//                    $menu              = new PagesMenu();
//                    $menu->page_id     = $model->id;
//                    $menu->model_type  = $item['class'];
//                    $menu->model_id    = $item['id'];
//                    $menu->order       = $order;
//                    $menu->model_title = $item['title'];
//                    $menu->model_slug  = $item['slug'];
//
//                    if (!$menu->save()) {
//                        DB::rollBack();
//                    }
//
//                    $order++;
//                }
//            }

            foreach (Langs::getLangsWithTitle() as $lang => $item) {
                $constructorData = $request->get('constructorData');
                $model->translateOrNew($lang)->fill(array_merge($request->input('page_data.' . $lang, []), $constructorData[$lang] ?? []));

                if (!$model->save()) {
                    DB::rollBack();
                }
            }
        } catch (\Throwable $e) {
            DB::rollBack();

            return redirect()->route('landing.index')->with('error', 'Ошибка! ' . $e->getMessage());
        }

        DB::commit();

//        $pageMenu = PagesMenu::query()
//            ->where('model_id',$model->id)
//            ->where('model_type',get_class($model))
//            ->get();
//
//        if(count($pageMenu)) {
//            foreach ($pageMenu as $pm){
//                $pm->model_title = $model->title;
//                $pm->model_slug = $model->slug;
//                $pm->save();
//            }
//        }


        return redirect()->back()->with('success', 'Лендинг успешно обновлен!');
    }

    /**
     * @param Landing $landing
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Landing $landing)
    {
        $landing->deleteTranslations();
        $landing->audio()->sync([]);
        $landing->delete();

        return redirect()->back()->with('success', 'Лендинг успешно удалено!');
    }
}

app/Http/Controllers/Api/LandingController.php
<?php

namespace App\Http\Controllers\Api;

use App\Core\Error\ErrorManager;
use App\Core\Response\ResponseTrait;
use App\Http\Controllers\Controller;
use App\Models\Landing;
use App\Models\Langs;
use App\Models\Pages;
use App\Models\PagesMenu;
use App\Modules\Setting\Setting;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Service\Adapter;

class LandingController extends Controller
{
    use ResponseTrait;

    private Adapter $adapter;

    public function __construct(Adapter $adapter)
    {
        $this->adapter = $adapter;
    }

    public function getBySlug(Request $request)
    {

        if (!$decodedJson = $request->json()->all()) {
            return $this->errorResponse(
                ErrorManager::buildError(VALIDATION_REQUEST_JSON_EXPECTED),
                Response::HTTP_UNPROCESSABLE_ENTITY
            );
        }

        if (!isset($decodedJson['slug'])) {
            return $this->errorResponse(
                ErrorManager::buildError(VALIDATION_REQUIRED_FIELD, ['slug']),
                Response::HTTP_UNPROCESSABLE_ENTITY
            );
        }

        if (isset($decodedJson['lang'])) {
            $lang = $decodedJson['lang'];
        } else {
            $lang = Langs::getDefaultLangCode();
        }

        $model = Landing::query()
            ->active()
            ->where('slug', $request->get('slug'))
            ->with('audio.category',function ($q) use($lang){
                $q->leftJoin('audio_category_translations','audio_category_translations.audio_categories_id','=','audio_categories.id')
                    ->where('audio_category_translations.lang',$lang)
                    ->select(['audio_categories.*','audio_category_translations.title AS categoryName']);
            })
            ->first();

        if (!$model)
            return $this->errorResponse(
                ErrorManager::buildError(VALIDATION_MODEL_NOT_FOUND),
                Response::HTTP_NOT_FOUND);


        $data = $this->adapter->prepareModelResults($model,$lang);

        /* landing 1 */
        if($model->id == 5){
            $menuId = 250;
        }
        /* landing 2 */
        elseif($model->id == 6){
            $menuId = 251;
        }

        if(isset($menuId)){
            $mainMenuTag = \App\Models\Menu::query()
                ->where('id',$menuId)
                ->where('const',  1)
                ->first();

            $menu = [];

            if($mainMenuTag){
                $menu = \App\Models\Menu::query()
                    ->where('tag', $mainMenuTag->tag)
                    ->where('const', '<>', 1)
                    ->with(['page','blog','landing','donor','plasmacentr'])
                    ->defaultOrder()
                    ->get()
                    ->toTree()
                    ->toArray();
            }

            $data['menu'] = count($menu) ? $this->adapter->prepareMenuResults($menu,$lang) : [];
        }

        return $this->successResponse($data);
    }
}

resources/views/admin/landing/_form.blade.php
<div class="form-group row">
    <label class="col-md-3 text-right" for="name">Изображение</label>
    <div class="col-md-9">
        {{ media_preview_box('image',$model->image) }}
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3 text-right" for="page_menu_id">Меню</label>
    <div class="col-md-9">
        <select name="menu_id" id="menu_id" class="select-field" style="width: 100%">
            <option value="">---</option>
            @foreach(\App\Models\Menu::getTagsWithId() as $menuId => $item)
                <option value="{{$menuId}}" @if(old('menu_id', $model->menu_id ?? '') == $menuId) selected @endif>{{$item}}</option>
            @endforeach
        </select>

        @if ($errors->has('menu_id'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('menu_id') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3 text-right" for="page_slug">Slug</label>
    <div class="col-md-9">
        <input type="text" name="slug" value="{{ old('slug', $model->slug ?? '') }}" id="page_slug" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}">

        @if ($errors->has('slug'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('slug') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3 text-right" for="page_status">Статус</label>
    <div class="col-md-9">
        <div class="material-switch pull-left">
            <input id="someSwitchOptionSuccess" name="status" value="1" type="checkbox" {{ old('status', $model->status) ? ' checked' : '' }}/>
            <label for="someSwitchOptionSuccess" class="label-success"></label>
        </div>

        @if ($errors->has('status'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('status') }}</strong>
            </span>
        @endif
    </div>
</div>

resources/views/admin/landing/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item"><a href="{{route('landing.index')}}">Лендинги</a></li>
            <li class="breadcrumb-item active" aria-current="page">Добавть</li>
        </ol>
    </nav>

    <form class="form-horizontal" method="POST" action="{{ route('landing.store') }}">
        @csrf

    <div class="row">
        <div class="col-md-12">
            <div class="card">

            <div class="card-header">
                <ul class="nav nav-tabs" id="myTab" role="tablist" style="margin-bottom: -10px;border-bottom: none">
                    <li class="nav-item">
                        <a class="nav-link active" id="main-tab" data-toggle="tab" href="#main" role="tab" aria-controls="main" aria-selected="true">Информация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="seo-tab" data-toggle="tab" href="#seo" role="tab" aria-controls="seo" aria-selected="false">SEO</a>
                    </li>
                </ul>
            </div>

             <div class="card-body">
                 <div class="tab-content" id="myTabContent">
                     {{----------------------------- MAIN TAB -----------------------------------------}}
                     <div class="tab-pane fade show active" id="main" role="tabpanel" aria-labelledby="main-tab">
                         <ul class="nav nav-tabs" role="tablist">
                             @foreach($localizations as $key => $lang)
                                 <li class="nav-item">
                                     <a class="nav-link @if(app()->getLocale() == $key) active @endif" data-toggle="tab" href="#main_lang_{{ $key }}" role="tab">
                                         <span class="hidden-sm-up"></span> <span class="hidden-xs-down">{{ $lang }}</span>
                                     </a>
                                 </li>
                             @endforeach
                         </ul>

                         <br>
                         <div class="tab-content">
                             @foreach($localizations as $key => $catLang)
                                 <div class="tab-pane p-t-20 p-b-20  @if(app()->getLocale() == $key) active @endif" id="main_lang_{{ $key }}" role="tabpanel">
                                     @include('admin.landing.tabs._main',[
                                        'lang' => $key,
                                        'model' => $model
                                     ])

                                     {!! Constructor::output(\App\Models\Translations\LandingTranslation::class,$key) !!}
                                 </div>
                             @endforeach

                             @include('admin.landing._form',['model' => $model])
                         </div>
                     </div>

                     {{----------------------------- SEO TAB -----------------------------------------}}
                     <div class="tab-pane fade" id="seo" role="tabpanel" aria-labelledby="seo-tab">
                         <ul class="nav nav-tabs" role="tablist">
                             @foreach($localizations as $key => $lang)
                                 <li class="nav-item">
                                     <a class="nav-link @if(app()->getLocale() == $key) active @endif" data-toggle="tab" href="#seo_lang_{{ $key }}" role="tab">
                                         <span class="hidden-sm-up"></span> <span class="hidden-xs-down">{{ $lang }}</span>
                                     </a>
                                 </li>
                             @endforeach
                         </ul>

                         <br>
                         <div class="tab-content tabcontent-border">
                             @foreach($localizations as $key => $catLang)
                                 <div class="tab-pane p-t-20 p-b-20  @if(app()->getLocale() == $key) active @endif" id="seo_lang_{{ $key }}" role="tabpanel">
                                     @include('admin.landing.tabs._seo',[
                                        'lang' => $key
                                     ])
                                 </div>
                             @endforeach
                         </div>
                     </div>
                 </div>

                 <input type="submit" value="Сохранить" class="btn btn-success text-white float-right">

             </div>
            </div>
        </div>
    </div>

    </form>
@endsection

@push('styles')
    <style>
        /*-- ==============================================================
        Switches
        ============================================================== */
        .material-switch {
            line-height: 3em;
        }
        .material-switch > input[type="checkbox"] {
            display: none;
        }

        .material-switch > label {
            cursor: pointer;
            height: 0px;
            position: relative;
            width: 40px;
        }

        .material-switch > label::before {
            background: rgb(0, 0, 0);
            box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.5);
            border-radius: 8px;
            content: '';
            height: 16px;
            margin-top: -8px;
            position:absolute;
            opacity: 0.3;
            transition: all 0.4s ease-in-out;
            width: 40px;
        }
        .material-switch > label::after {
            background: rgb(255, 255, 255);
            border-radius: 16px;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
            content: '';
            height: 24px;
            left: -4px;
            margin-top: -8px;
            position: absolute;
            top: -4px;
            transition: all 0.3s ease-in-out;
            width: 24px;
        }
        .material-switch > input[type="checkbox"]:checked + label::before {
            background: inherit;
            opacity: 0.5;
        }
        .material-switch > input[type="checkbox"]:checked + label::after {
            background: inherit;
            left: 20px;
        }
    </style>
@endpush

resources/views/admin/landing/index.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item active" aria-current="page">Лендинги</li>
        </ol>
    </nav>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form action="" method="get">
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label>Статус</label>
                            <select name="status" class="select2 form-control m-t-15">
                                <option value="">---</option>
                                @foreach(\App\Models\Landing::getStatuses() as $key => $item)
                                    <option value="{{$key}}" @if(old('status', request()->input('status')) == (string)$key) selected @endif>{{$item}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group col-md-2">
                            <label>Поиск</label>
                            <input type="text" class="form-control" name="title" value="{{old('title', request()->input('title'))}}">
                        </div>

                        <div class="form-group col-md-1">
                            <label for="inputPassword4">&nbsp;</label>
                            <button type="submit" class="btn btn-success form-control text-white">Фильтровать</button>
                        </div>
                        <div class="form-group col-md-1">
                            <label for="inputPassword4">&nbsp;</label>
                            <a href="{{ route('landing.index') }}" class="btn btn-danger form-control text-white">Сбросить</a>
                        </div>
                    </div>
                </form>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Заголовок</th>
                            <th>URL</th>
                            <th>Статус</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($model as $item)
                            <tr data-id="{{$item->id}}">
                                <td>{{$item->id}}</td>
                                <td>
                                    <a href="{{ route('landing.edit', $item->id) }}">
                                        {{$item->title}}
                                    </a></td>
                                <td>{{$item->slug}}</td>
                                <td>
                                    <span class="badge"
                                          style="color: {{\App\Models\Landing::getStatusColors()[$item->status][1]}}; background-color:{{\App\Models\Landing::getStatusColors()[$item->status][0]}}"
                                    >{{\App\Models\Landing::getStatuses()[$item->status]}}</span>
                                </td>
                                <td>
                                    <div style="display: flex">
                                        <div style="margin-left: 10px">
                                            <form action="{{ route('landing.destroy', $item->id) }}" method="POST">

                                                <a href="/{{$item->slug}}" target="_blank" title="Посмотреть на сайте" class="btn btn-info  btn-xs"><i class="fa fa-eye"></i></a>

                                                <a href="{{ route('landing.edit', $item->id) }}" class="btn btn-xs btn-primary">
                                                    <i class="fas fa-edit fa-lg"></i>
                                                </a>

                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $model->appends(request()->all())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $(document).ready(() => {
            $('.delete-item-btn').on('click',function() {
                if(confirm('Вы пытаетесь удалить запись?')){
                    $(this).closest('form').submit();
                }
            });
        });
    </script>
@endpush