routes/web.php
<?php

use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Support\Facades\Route;

/* @var $localeMiddleware LocaleMiddleware */
$localeMiddleware = app( LocaleMiddleware::class);

\Illuminate\Support\Facades\Auth::routes();

Route::get('cache-clear',function (){
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');

    return redirect()->back()->with('success','Кеш успешно очищено!');
})->name('cache-clear');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('/admin/login', [\App\Http\Controllers\Admin\HomeController::class,'login'])->name('admin.login');

/*********************************************** ADMIN ****************************************************************/
Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::post('/export-table', [\App\Http\Controllers\Admin\ExportTableController::class,'export'])->name('export-table');
    Route::get('/', [\App\Http\Controllers\Admin\HomeController::class,'index'])->name('admin');
    Route::resource('/users-admin', \App\Http\Controllers\Admin\UserAdminController::class);
    Route::get('/users/{id}/{tab}', [\App\Http\Controllers\Admin\UsersController::class,'getTab'])->where('tab', '[a-z0-9-]+');
    Route::post('/users-change-status', [\App\Http\Controllers\Admin\UsersController::class,'changeStatus'])->name('user.change-status');
    Route::resource('/users', \App\Http\Controllers\Admin\UsersController::class);
    Route::post('/pages/menu/add-item', [\App\Http\Controllers\Admin\PagesController::class,'addItem'])->name('page.add-item');
    Route::resource('/pages', \App\Http\Controllers\Admin\PagesController::class);
    Route::resource('/landing', \App\Http\Controllers\Admin\LandingController::class);
    Route::resource('/donors', \App\Http\Controllers\Admin\DonorsController::class);
    Route::post('/plasmacenters/add-social', [\App\Http\Controllers\Admin\PlasmacenterController::class,'addSocial'])->name('plasmacenters.add-social');
    Route::resource('/plasmacenters', \App\Http\Controllers\Admin\PlasmacenterController::class);
    Route::post('menu/move', [\App\Http\Controllers\Admin\MenuController::class,'move']);
    Route::post('menu/rebuild', [\App\Http\Controllers\Admin\MenuController::class,'rebuild']);
    Route::post('menu/add-item', [\App\Http\Controllers\Admin\MenuController::class,'addItem'])->name('menu.add-item');
    Route::post('menu/delete-menu', [\App\Http\Controllers\Admin\MenuController::class,'deleteMenu'])->name('menu.delete-menu');
    Route::post('menu/add-menu', [\App\Http\Controllers\Admin\MenuController::class,'addMenu'])->name('menu.add-menu');
    Route::resource('/menu', \App\Http\Controllers\Admin\MenuController::class);
    Route::resource('/faq', \App\Http\Controllers\Admin\FaqController::class);
    Route::get('settings/{tab}', [\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('add-notice')->where('tab', '[a-z0-9-]+');
    Route::post('settings/save', [\App\Http\Controllers\Admin\SettingsController::class,'save'])->name('settings.save');
    Route::resource('/audio', \App\Http\Controllers\Admin\AudioController::class);
    Route::resource('/audio-categories', \App\Http\Controllers\Admin\AudioCategoryController::class);
    Route::post('/request/status/change', [\App\Http\Controllers\Admin\RequestController::class,'changeStatus'])->name('request.status-change');
    Route::resource('/request', \App\Http\Controllers\Admin\RequestController::class);

    /** BLOG **/
    Route::group(['prefix' => 'blog'], function () {
        Route::resource('/tags', \App\Http\Controllers\Admin\BlogTagsController::class);
        Route::resource('/articles', \App\Http\Controllers\Admin\BlogArticlesController::class);
        Route::get('/subscribe', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'index'])->name('subscribe.index');
        Route::get('/subscribe/list', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'list'])->name('subscribe.list');
    });
});
/************************************ END ADMIN ***********************************************************************/

Route::group(['namespace' => 'Front'], function(){
    Route::any('/{any}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');


    Route::any('/donors/{donor}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');
    Route::any('/{any}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');
});
/*******************************************************************/

resources/views/layouts/admin/components/aside.blade.php
<?php

use Illuminate\Support\Facades\Request;

?>

<aside class="left-sidebar" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="pt-4">
                <li class="sidebar-item @if(in_array(Request::segment(1),['admin']) && Request::segment(2) == '') active @endif">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('admin')}}" aria-expanded="false">
                        <i class="mdi mdi-blur-linear"></i>
                        <span class="hide-menu">Панель приборов</span>
                    </a>
                </li>

{{--                <li class="sidebar-item @if(in_array(Request::segment(2),['users'])) active @endif">--}}
{{--                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('users.index')}}" aria-expanded="false">--}}
{{--                        <i class="mdi mdi-account"></i>--}}
{{--                        <span class="hide-menu">Пользователи</span>--}}
{{--                    </a>--}}
{{--                </li>--}}

                <li class="sidebar-item @if(in_array(Request::segment(2),['pages'])) active @endif">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('pages.index')}}" aria-expanded="false">
                        <i class="mdi mdi-book-open-page-variant"></i>
                        <span class="hide-menu">Страницы</span>
                    </a>
                </li>

                <li class="sidebar-item @if(in_array(Request::segment(2),['landing'])) active @endif">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('landing.index')}}" aria-expanded="false">
                        <i class="mdi mdi-view-list"></i>
                        <span class="hide-menu">Лендинги</span>
                    </a>
                </li>

                <li class="sidebar-item @if(in_array(Request::segment(2),['donors'])) active @endif">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('donors.index')}}" aria-expanded="false">
                        <i class="mdi mdi-medical-bag"></i>
                        <span class="hide-menu">Доноры</span>
                    </a>
                </li>

                <li class="sidebar-item @if(in_array(Request::segment(2),['plasmacenters'])) active @endif">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('plasmacenters.index')}}" aria-expanded="false">
                        <i class="mdi mdi-hospital-building"></i>
                        <span class="hide-menu">Плазмацентры</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                        <i class="mdi mdi-newspaper"></i>
                        <span class="hide-menu">Блог</span>
                    </a>
                    <ul aria-expanded="false" class="collapse  first-level">
                        <li class="sidebar-item @if(in_array(Request::segment(3),['articles'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('articles.index')}}" aria-expanded="false">
                                <i class="mdi mdi-message-outline"></i>
                                <span class="hide-menu">Публикации</span>
                            </a>
                        </li>

                        <li class="sidebar-item @if(in_array(Request::segment(3),['tags'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('tags.index')}}" aria-expanded="false">
                                <i class="mdi mdi-tag"></i>
                                <span class="hide-menu">Теги</span>
                            </a>
                        </li>

                        <li class="sidebar-item @if(in_array(Request::segment(3),['subscribe'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('subscribe.index')}}" aria-expanded="false">
                                <i class="mdi mdi-email"></i>
                                <span class="hide-menu">Подписки</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="sidebar-item @if(in_array(Request::segment(2),['faq'])) active @endif">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('faq.index')}}" aria-expanded="false">
                        <i class="mdi mdi-comment-question-outline"></i>
                        <span class="hide-menu">Частые вопросы</span>
                    </a>
                </li>

                <li class="sidebar-item @if(in_array(Request::segment(2),['request'])) active @endif">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('request.index')}}" aria-expanded="false">
                        <i class="mdi mdi-pen"></i>
                        <span class="hide-menu">Онлайн записи</span>
                    </a>
                </li>

                <li class="sidebar-item @if(in_array(Request::segment(2),['users-admin'])) active @endif">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('users-admin.index')}}" aria-expanded="false">
                        <i class="mdi mdi-account"></i>
                        <span class="hide-menu">Администраторы</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                        <i class="mdi mdi-format-paint"></i>
                        <span class="hide-menu">Внешний вид </span>
                    </a>
                    <ul aria-expanded="false" class="collapse  first-level">

                        <li class="sidebar-item @if(in_array(Request::segment(2),['widgets'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/admin/widgets" aria-expanded="false">
                                <i class="mdi mdi-widgets"></i>
                                <span class="hide-menu">Виджеты</span>
                            </a>
                        </li>

                        <li class="sidebar-item @if(in_array(Request::segment(2),['menu'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('menu.index')}}" aria-expanded="false">
                                <i class="mdi mdi-menu"></i>
                                <span class="hide-menu">Меню</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                        <i class="mdi mdi-audiobook"></i>
                        <span class="hide-menu">Аудио треки </span>
                    </a>
                    <ul aria-expanded="false" class="collapse  first-level">

                        <li class="sidebar-item @if(in_array(Request::segment(2),['audio-categories'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('audio-categories.index')}}" aria-expanded="false">
                                <i class="mdi mdi-tag"></i>
                                <span class="hide-menu">Категории</span>
                            </a>
                        </li>

                        <li class="sidebar-item @if(in_array(Request::segment(2),['audio'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('audio.index')}}" aria-expanded="false">
                                <i class="mdi mdi-audiobook"></i>
                                <span class="hide-menu">Треки</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                        <i class="mdi mdi-settings"></i>
                        <span class="hide-menu">Настройки</span>
                    </a>
                    <ul aria-expanded="false" class="collapse  first-level">
                        <li class="sidebar-item @if(in_array(Request::segment(4),['main'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/admin/settings/main" aria-expanded="false">
                                <i class="mdi mdi-checkbox-blank-circle-outline"></i>
                                <span class="hide-menu">Главные</span>
                            </a>
                        </li>

                        <li class="sidebar-item @if(in_array(Request::segment(4),['contacts'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/admin/settings/contacts" aria-expanded="false">
                                <i class="mdi mdi-checkbox-blank-circle-outline"></i>
                                <span class="hide-menu">Контакты</span>
                            </a>
                        </li>
                        <li class="sidebar-item @if(in_array(Request::segment(4),['blog'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/admin/settings/blog" aria-expanded="false">
                                <i class="mdi mdi-checkbox-blank-circle-outline"></i>
                                <span class="hide-menu">Блог</span>
                            </a>
                        </li>
                        <li class="sidebar-item @if(in_array(Request::segment(4),['page'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/admin/settings/page" aria-expanded="false">
                                <i class="mdi mdi-checkbox-blank-circle-outline"></i>
                                <span class="hide-menu">Страницы</span>
                            </a>
                        </li>
                        <li class="sidebar-item @if(in_array(Request::segment(4),['donors'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/admin/settings/donors" aria-expanded="false">
                                <i class="mdi mdi-checkbox-blank-circle-outline"></i>
                                <span class="hide-menu">Доноры</span>
                            </a>
                        </li>
                        <li class="sidebar-item @if(in_array(Request::segment(4),['plasmacenters'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/admin/settings/plasmacenters" aria-expanded="false">
                                <i class="mdi mdi-checkbox-blank-circle-outline"></i>
                                <span class="hide-menu">Плазмацентры</span>
                            </a>
                        </li>
                        <li class="sidebar-item @if(in_array(Request::segment(4),['faq'])) active @endif">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/admin/settings/faq" aria-expanded="false">
                                <i class="mdi mdi-checkbox-blank-circle-outline"></i>
                                <span class="hide-menu">Частые вопросы</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>

resources/views/layouts/admin/components/header.blade.php
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin5">

            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="{{route('admin')}}">
                <!-- Logo icon -->
                <b class="logo-icon ps-2">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="{{asset('matrix/images/logo-icon.png')}}" alt="homepage" class="light-logo" />

                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                            <!-- dark Logo text -->
                            <img src="{{asset('matrix/images/logo-text.png')}}" alt="homepage" class="light-logo" />

                        </span>
                <!-- Logo icon -->
                <!-- <b class="logo-icon"> -->
                <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                <!-- Dark Logo icon -->
                <!-- <img src="../../assets/images/logo-text.png" alt="homepage" class="light-logo" /> -->

                <!-- </b> -->
                <!--End Logo icon -->
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
                    class="ti-menu ti-close"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-start me-auto">
                <li class="nav-item d-none d-lg-block"><a
                        class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)"
                        data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                <!-- ============================================================== -->
                <!-- create new -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                        <span class="d-none d-md-block">Добавити <i class="fa fa-angle-down"></i></span>
                        <span class="d-block d-md-none"><i class="fa fa-plus"></i></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{route('pages.create')}}">Сторінку</a></li>
                        <li><a class="dropdown-item" href="{{route('articles.create')}}">Публікацію</a></li>
{{--                        <li><hr class="dropdown-divider"></li>--}}
                    </ul>
                </li>
                <!-- ============================================================== -->
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-end">
                <!-- ============================================================== -->
                <!-- Comment -->
                <!-- ============================================================== -->
{{--                <li class="nav-item dropdown">--}}
{{--                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">--}}
{{--                        <i class="mdi mdi-bell font-24"></i>--}}
{{--                    </a>--}}
{{--                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">--}}
{{--                        <li><a class="dropdown-item" href="#">Action</a></li>--}}
{{--                        <li><a class="dropdown-item" href="#">Another action</a></li>--}}
{{--                        <li><hr class="dropdown-divider"></li>--}}
{{--                        <li><a class="dropdown-item" href="#">Something else here</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
{{--                <li class="nav-item dropdown">--}}
{{--                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="#" id="2" role="button" data-bs-toggle="dropdown" aria-expanded="false">--}}
{{--                        <i class="font-24 mdi mdi-comment-processing"></i>--}}
{{--                    </a>--}}
{{--                    <ul class="dropdown-menu dropdown-menu-end mailbox animated bounceInDown" aria-labelledby="2">--}}
{{--                        <ul class="list-style-none">--}}
{{--                            <li>--}}
{{--                                <div class="">--}}
{{--                                    <!-- Message -->--}}
{{--                                    <a href="javascript:void(0)" class="link border-top">--}}
{{--                                        <div class="d-flex no-block align-items-center p-10">--}}
{{--                                                    <span class="btn btn-success btn-circle"><i--}}
{{--                                                            class="ti-calendar"></i></span>--}}
{{--                                            <div class="ms-2">--}}
{{--                                                <h5 class="mb-0">Event today</h5>--}}
{{--                                                <span class="mail-desc">Just a reminder that event</span>--}}
{{--                                            </div>--}}
{{--                                        </div>--}}
{{--                                    </a>--}}
{{--                                    <!-- Message -->--}}
{{--                                    <a href="javascript:void(0)" class="link border-top">--}}
{{--                                        <div class="d-flex no-block align-items-center p-10">--}}
{{--                                                    <span class="btn btn-info btn-circle"><i--}}
{{--                                                            class="ti-settings"></i></span>--}}
{{--                                            <div class="ms-2">--}}
{{--                                                <h5 class="mb-0">Settings</h5>--}}
{{--                                                <span class="mail-desc">You can customize this template</span>--}}
{{--                                            </div>--}}
{{--                                        </div>--}}
{{--                                    </a>--}}
{{--                                    <!-- Message -->--}}
{{--                                    <a href="javascript:void(0)" class="link border-top">--}}
{{--                                        <div class="d-flex no-block align-items-center p-10">--}}
{{--                                                    <span class="btn btn-primary btn-circle"><i--}}
{{--                                                            class="ti-user"></i></span>--}}
{{--                                            <div class="ms-2">--}}
{{--                                                <h5 class="mb-0">Pavan kumar</h5>--}}
{{--                                                <span class="mail-desc">Just see the my admin!</span>--}}
{{--                                            </div>--}}
{{--                                        </div>--}}
{{--                                    </a>--}}
{{--                                    <!-- Message -->--}}
{{--                                    <a href="javascript:void(0)" class="link border-top">--}}
{{--                                        <div class="d-flex no-block align-items-center p-10">--}}
{{--                                                    <span class="btn btn-danger btn-circle"><i--}}
{{--                                                            class="fa fa-link"></i></span>--}}
{{--                                            <div class="ms-2">--}}
{{--                                                <h5 class="mb-0">Luanch Admin</h5>--}}
{{--                                                <span class="mail-desc">Just see the my new admin!</span>--}}
{{--                                            </div>--}}
{{--                                        </div>--}}
{{--                                    </a>--}}
{{--                                </div>--}}
{{--                            </li>--}}
{{--                        </ul>--}}
{{--                    </ul>--}}
{{--                </li>--}}
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->

                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item d-none d-lg-block" title="Очистить кеш">
                    <a class="nav-link sidebartoggler waves-effect waves-light" href="{{route('cache-clear')}}"
                       data-sidebartype="mini-sidebar">
                        <i class="mdi mdi-cached font-24"></i>
                    </a>
                </li>
                <li class="nav-item d-none d-lg-block">
                    <a class="nav-link sidebartoggler waves-effect waves-light" href="/" target="_blank"
                       data-sidebartype="mini-sidebar">
                        <i class="mdi mdi-eye font-24"></i>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{asset('matrix/images/users/1.jpg')}}" alt="user" class="rounded-circle" width="31">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end user-dd animated" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/admin/users-admin/{{\Illuminate\Support\Facades\Auth::id()}}/edit"><i class="ti-user me-1 ms-1"></i>
                            Мій профіль</a>
{{--                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-wallet me-1 ms-1"></i>--}}
{{--                            My Balance</a>--}}
{{--                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-email me-1 ms-1"></i>--}}
{{--                            Inbox</a>--}}
{{--                        <div class="dropdown-divider"></div>--}}
{{--                        <a class="dropdown-item" href="javascript:void(0)"><i--}}
{{--                                class="ti-settings me-1 ms-1"></i> Account Setting</a>--}}
{{--                        <div class="dropdown-divider"></div>--}}
                        <a class="dropdown-item" href="javascript:void(0)" onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i
                                class="fa fa-power-off me-1 ms-1"></i> Вихід</a>
                        <div class="dropdown-divider"></div>
                    </ul>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>